project_id         = "terrakube"
certmanager_email  = "bjuglas@crystalchain.io"
region             = "europe-west4"
gitlab_db_password = "FDsHVkEIUKHZ6eH8nD35t1Ek"
domain             = "ccc.crystalchain.io"
gitlab_address_name = "gitlab"
